apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: gardener-extension-validator-gcp
webhooks:
- name: validation.gcp.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  clientConfig:
    url: "https://localhost:9443/webhooks/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLRENDQWhDZ0F3SUJBZ0lVR1VqMFNROVpJeXFUSmsvV0owbk5yQzl0azZjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xERVJNQThHQTFVRUNoTUlSMkZ5WkdWdVpYSXhGekFWQmdOVkJBTVREbWRoY21SbGJtVnlMbU5zYjNWawpNQjRYRFRJd01ETXdPVEE0TkRVd01Gb1hEVEkxTURNd09EQTRORFV3TUZvd0xERVJNQThHQTFVRUNoTUlSMkZ5ClpHVnVaWEl4RnpBVkJnTlZCQU1URG1kaGNtUmxibVZ5TG1Oc2IzVmtNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0K1FMaG1KT2xIcW9CYnpPdHlTWVNzTzMrb3F5YmtiY2kxVnJaOXhOTHl1MwphRXlkWEFCQkJCTzMzckNuL2xLeXpodERFdjZHMVhlaWJVS1dKalBqV250K3lTK3NwMHA4L1p3YW9LdGh4SVpGClAyTlVMRmFneWhVU2ZIVm9WbGY1MklabXJwQWVGVzVRKzEzNm9seTFCZnZDYmhsTnZGcVhjQnZRY0VDNzhYTmoKMlc1Q0tmYlhvRjJEZnVqb3JRb1M1WGVpM2JzN3NQQmJDRlJIc1h4RHNxMVE4REY1ZG1yZStWVHdxRjdreTdiTAp6TEsrVkFsNFJZaTNnNTdUdEo2TUVQMWp2a2N2SnIycVNoUXZmY3VPS0tiaENVUG5ZdjQ3UE5ZMkZWY2RTTzJBClFGcmgwNHIwQjR3azdjT3hGWFM5cEJ5NGtYQ1EwbkNXdTJjblExNWpiUUlEQVFBQm8wSXdRREFPQmdOVkhROEIKQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVQ2VHOEluVzUvUUlDem1LNApaRFZFMTZHbGo5WXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSytWODhSdWp4TzR5ZEZXWXhCaGliUVhWMFZHCks1NWRGdzVpS1ZmTFAvdHphTVI5b2ZQbi90Rmw5bGpVM3p1V0FURTVZdkVxWjFIY3diSlJZeXpueVI5QWVwdmkKM213L1dTQktzUHZOME1RWUw0ZStUZWxvU3RueXc2TEFlbXFQMVprejdST3Y5bVE2L0VkUlhYWnBhbkxjb0FQRgpSQUtQN1BCNXA4Y2RHc3prN2xpbmUxZGdIaHUzOVhLdzJhaUI0d0l1d3AvY2ZZV01IN2MrTnhIN2lvc3pLb1ZPCkVEMm1UYVZEQ1QxSWlXQ2xuSmVFaExla3dPNy8zYm5ZRWtnR05HLzU0d3AxUU1lSEVqVDUxQnE0QjNiYkhBRGMKL2svbUpXOWJUcld2NzlYdUwvSkJJdmNzdFJSK0VmcHZWMUMxbmNtSnUvWkhyaEpNbUcxQnJiSXRjaEU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
