apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: gardener-extension-admission-gcp
webhooks:
- name: validation.gcp.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudprofiles
    - shoots
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  clientConfig:
    url: "https://localhost:9443/webhooks/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLRENDQWhDZ0F3SUJBZ0lVZDMzcEpWL01RWm12eENPU3FtdmpCOStvTENBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xERVJNQThHQTFVRUNoTUlSMkZ5WkdWdVpYSXhGekFWQmdOVkJBTVREbWRoY21SbGJtVnlMbU5zYjNWawpNQjRYRFRJd01EVXpNVEUxTlRjd01Gb1hEVEkxTURVek1ERTFOVGN3TUZvd0xERVJNQThHQTFVRUNoTUlSMkZ5ClpHVnVaWEl4RnpBVkJnTlZCQU1URG1kaGNtUmxibVZ5TG1Oc2IzVmtNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0TkhXcENKbEMvYnIwM3VKUyt6MkgxNWlpSXBHQlJyMkpNV09ZbEhUVWYwNgpIYkFZbHhzTTR0bUZhUnZ4d0NRRlc2TnZ5cml0dWM2RCs0Q21YZFR1Z2QvaThVS2lNcU1wbXVVbHY5akhqUGVECnI0clBHeU1rZllHRm5HMGpua2RidXE1UDRDZTlLOXVCMytDekl2VGNoRklNVnE3d0dIMHJJYTBMQlVpSmlqUUsKMmYzNVNueTFvYlhlTm05V01TYUVrYjRndXlyUjlvK0FXSmlNd2hrWXIwSnlBeXV0M2wxcE9IMkpuU2ZHdXBCLwozYmFGWUlWbnVBQm1BSzUrNUxSUktTNzF3NUFXV0IvR2x5YzMzWlUwQXZNczVwRmFZaUNrVzVkbzdXS0NDU08wClpQNSttVHVhbGRJQ1gvSUpBWi9oZWRsRHZUVEs3L2V3UlBtK0tFbWppd0lEQVFBQm8wSXdRREFPQmdOVkhROEIKQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVSmlSTTdXb1doSDlqYWdzZgpFZWllZGFITVROOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR200MlQxL243SG1nMEtuRW1jQlcvTFdKaTUzCkpiU3VHWmZOOEltY1dHUkg4RXlhVGhseUxHa201U29OcFV3Y0c2b0JGZUR6dE9KbFZuV05JT1FYNndqVHhtcE0KK2o5d3hJSWpId2Q1emZoSm1xUE5GVlY1OVlvc1M2bWx2R2J5V09vSDBKRTRqVTNHamFvN1dkK21qYzRBQ21kMgpRNDlsZENrd2ZtTHQ5Y0hWSDNYNHNURDJRVmp4MFM1YU5nNkdKOHdFQnFabzl1Tlpyc0NOa21HbUZ5RXlLTDVmClRNQmJtNkZ3MzR2UFRnaEdGeFVQSzJ2Tk1mVStFa1EyTllkUURwQVJlQXNlalhuRmpvZ2RnQjRvcm4vUENwQjYKMGZPMVlIcjAvRDVoV1NMLzFINkF2V0NjT1N5ZjJSRVVDMzRJSTR3RGxVUjhsMVBwOEVPeW5DN2Raa0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
- name: secrets.validation.gcp.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - secrets
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  clientConfig:
    service:
      namespace: garden
      name: gardener-extension-admission-gcp
      path: /webhooks/validate/secrets
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLRENDQWhDZ0F3SUJBZ0lVZDMzcEpWL01RWm12eENPU3FtdmpCOStvTENBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xERVJNQThHQTFVRUNoTUlSMkZ5WkdWdVpYSXhGekFWQmdOVkJBTVREbWRoY21SbGJtVnlMbU5zYjNWawpNQjRYRFRJd01EVXpNVEUxTlRjd01Gb1hEVEkxTURVek1ERTFOVGN3TUZvd0xERVJNQThHQTFVRUNoTUlSMkZ5ClpHVnVaWEl4RnpBVkJnTlZCQU1URG1kaGNtUmxibVZ5TG1Oc2IzVmtNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0TkhXcENKbEMvYnIwM3VKUyt6MkgxNWlpSXBHQlJyMkpNV09ZbEhUVWYwNgpIYkFZbHhzTTR0bUZhUnZ4d0NRRlc2TnZ5cml0dWM2RCs0Q21YZFR1Z2QvaThVS2lNcU1wbXVVbHY5akhqUGVECnI0clBHeU1rZllHRm5HMGpua2RidXE1UDRDZTlLOXVCMytDekl2VGNoRklNVnE3d0dIMHJJYTBMQlVpSmlqUUsKMmYzNVNueTFvYlhlTm05V01TYUVrYjRndXlyUjlvK0FXSmlNd2hrWXIwSnlBeXV0M2wxcE9IMkpuU2ZHdXBCLwozYmFGWUlWbnVBQm1BSzUrNUxSUktTNzF3NUFXV0IvR2x5YzMzWlUwQXZNczVwRmFZaUNrVzVkbzdXS0NDU08wClpQNSttVHVhbGRJQ1gvSUpBWi9oZWRsRHZUVEs3L2V3UlBtK0tFbWppd0lEQVFBQm8wSXdRREFPQmdOVkhROEIKQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVSmlSTTdXb1doSDlqYWdzZgpFZWllZGFITVROOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR200MlQxL243SG1nMEtuRW1jQlcvTFdKaTUzCkpiU3VHWmZOOEltY1dHUkg4RXlhVGhseUxHa201U29OcFV3Y0c2b0JGZUR6dE9KbFZuV05JT1FYNndqVHhtcE0KK2o5d3hJSWpId2Q1emZoSm1xUE5GVlY1OVlvc1M2bWx2R2J5V09vSDBKRTRqVTNHamFvN1dkK21qYzRBQ21kMgpRNDlsZENrd2ZtTHQ5Y0hWSDNYNHNURDJRVmp4MFM1YU5nNkdKOHdFQnFabzl1Tlpyc0NOa21HbUZ5RXlLTDVmClRNQmJtNkZ3MzR2UFRnaEdGeFVQSzJ2Tk1mVStFa1EyTllkUURwQVJlQXNlalhuRmpvZ2RnQjRvcm4vUENwQjYKMGZPMVlIcjAvRDVoV1NMLzFINkF2V0NjT1N5ZjJSRVVDMzRJSTR3RGxVUjhsMVBwOEVPeW5DN2Raa0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
