run:
  concurrency: 4
  deadline: 10m

linters:
  disable:
  - unused
  enable:
  - revive

issues:
  exclude-use-default: false
  exclude:
  # revive
  - var-naming # ((var|const|struct field|func) .* should be .*
  - package-comments # package comment should be of the form

