{{- if .Values.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: csi-driver-node
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: csi-driver-node
  updatePolicy:
    updateMode: "Auto"
{{- end }}
