---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "ip-masq-agent.extensionsGroup" . }}.{{ include "ip-masq-agent.name" . }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
  - configMap
  hostNetwork: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
      rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
