apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "ip-masq-agent.extensionsGroup" . }}:psp:{{ include "ip-masq-agent.name" . }}"
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "ip-masq-agent.extensionsGroup" . }}:psp:{{ include "ip-masq-agent.name" . }}"
subjects:
  - kind: ServiceAccount
    name: ip-masq-agent
    namespace: kube-system