apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ip-masq-agent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      k8s-app: ip-masq-agent
  template:
    metadata:
      labels:
        k8s-app: ip-masq-agent
    spec:
      serviceAccount: ip-masq-agent
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - args:
            - --masq-chain=IP-MASQ
          image: {{ index .Values.images "ip-masq-agent" }}
          imagePullPolicy: IfNotPresent
          name: ip-masq-agent
          securityContext:
            privileged: true
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /etc/config
              name: config
      volumes:
        # this configmap is optional, i.e., it does not have to exist at creation time. It can however be created
        # to reconfigure the default behavior of the ip-masq-agent on a live-cluster.
        - configMap:
            defaultMode: 420
            items:
              - key: config
                path: ip-masq-agent
            name: ip-masq-agent
            optional: true
          name: config