{{- if not .Values.global.virtualGarden.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
{{- end }}
